version: '3'

services:
  jira:
    depends_on:
      - postgresql
    image: atlassian/jira-software
    networks:
      - jira-bitbucket
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '8080:8080'
    environment:
      - 'ATL_JDBC_URL=jdbc:postgresql://172.17.0.1:5432'
      - 'ATL_JDBC_PASSWORD='
      - 'ATL_JDBC_USER='

  postgresql:
    image: postgres:10
    networks:
      - jira-bitbucket
    volumes:
      - postgresqldata:/var/lib/postgresql/data 
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER='
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_DB='
  
  bitbucket:
    depends_on: 
      - bitbucketx
    image: atlassian/bitbucket-server:7.10.0
    networks: 
      - jira-bitbucket
    volumes: 
      - bitbucketdata:/var/atlassian/application-data/bitbucket
    ports:
      - '7990:7990'
    environment:
      - 'JDBC_DRIVER=org.postgresql.Driver' 
      - 'JDBC_USER='
      - 'JDBC_PASSWORD='
      - 'JDBC_URL=jdbc:postgresql://172.17.0.1:5433/bitbucketdb'
  
  bitbucketx:
    image: postgres:10
    networks:
      - jira-bitbucket
    volumes:
      - postgresqldatax:/var/lib/postgresql/data 
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_USER='
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_DB='
  

volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false
  bitbucketdata:
    external: false
  postgresqldatax:
    external: false



networks:
  jira-bitbucket:
    driver: bridge

